### ISSUE TITLE
Enemies cannot roll damage from the chat.

### ISSUE THREAD

**Issue by Hatbringer** [Lee-Talman/knave2e#11]
Currently, this button does nothing.
![image](https://github.com/Lee-Talman/knave2e/assets/63872053/f0d2f940-e340-4acd-8c95-30e87be100d5)

**Comment by Hatbringer** [comment]
Also, would be nice if upon rolling damage, the system printed out the attack description.

**Comment by Lee-Talman** [comment]
Couldn't reproduce this one locally or on my web-hosted server. Will chalk this up to "magically works on my machine" for now and see if it still pops up for you in 0.2.2.

**Comment by Lee-Talman** [comment]
> Also, would be nice if upon rolling damage, the system printed out the attack description.

This was added with #12
