### ISSUE TITLE
Option to manual enter damage dice instead of dropdown

### ISSUE THREAD

**Issue by Hatbringer** [Lee-Talman/knave2e#16]
Currently the weapon item uses three elements to specify damage type. This could be simplified into just a single element that also allows for unusual dice to be used (1d2, 1d3, 1d5, 1d20, 1d100), using standard dice notation. Doing so would improve ease of use, visual clarity, and freedom of customization. 

![image](https://github.com/Lee-Talman/knave2e/assets/63872053/0746497d-803d-43bd-a49b-e552a262bead)

**Comment by Lee-Talman** [comment]
Noted. Will check how feasible this is to change with a data migration. If it's straightforward it'll end up in 0.3.1. If not, will still get changed but will end up in 0.4 (the Foundry v12 release).
