### ISSUE TITLE
Can't open Actor Sheets with "Simple Calendar" Mod active

### ISSUE THREAD

**Issue by MMDaemon** [Lee-Talman/knave2e#17]
I used the "Simple Calendar" Module with multiple other Systems and did not have any  issues.
When i have the Mod active with the knave2e system I can't open the actor sheets anymore.

I get the following error:

```
foundry.js:753
Error: An error occurred while rendering Knave2eActorSheet 43. This is not a registered game setting
[Detected 1 package: system:knave2e]
    at ClientSettings.get (foundry.js:3339:42)
    at Knave2eActorSheet.getData (actor-sheet.mjs:54:51)
    at async Knave2eActorSheet._render (foundry.js:5812:18)
    at async Knave2eActorSheet._render (foundry.js:6532:5)
```

If you would be willing to look into even if it only occurs when using a mod, I would really appreciate it.

**Comment by Lee-Talman** [comment]
I use Simple Calendar and have had it active throughout development of Knave 2E. I would use a testing module like Find the culprit! to test and see if this is really Simple Calendar throwing this error here, or just incompatibility with a different mod, before I close this as un-reproducible.

**Comment by MMDaemon** [comment]
Thanks for looking into it.

I did as you said and got the following result:
![image](https://github.com/Lee-Talman/knave2e/assets/16777504/00c4ed0f-63ce-4054-adfa-c5ae74b97e8a)

For context, this is the list of mods i'm using:
![image](https://github.com/Lee-Talman/knave2e/assets/16777504/d84304c4-bcbd-48b5-92e2-434c15814011)

Still the same error:
![image](https://github.com/Lee-Talman/knave2e/assets/16777504/f7217a7a-ec51-4e70-80fa-3c8b13fe6b2b)
