### ISSUE TITLE
Option to disable certain quality of life features in the system settings

### ISSUE THREAD

**Issue by Hatbringer** [Lee-Talman/knave2e#9]
The system ships with some incredibly useful features that streamline running the game for the GM. However, not all GMs will want to use all of the features. Allowing features to be enabled or disabled in the system settings could allow for greater flexibility when making rulings, or enable more compatibility with homebrew rulings.

**Some features that could be easily toggelable without changing the spirit of the system:**
- Automatic Coin weight
- Automatic Bullet weight
- Automatic AP&AC calculation
- Automatic level calculation
- Automatic wound maximum calculation
- Automatic spellbook toggle on cast

**Some features that could allow for further customization:**
- Custom coin weight / coins per slot
- Custom bullet weight / Bullets per slot
- Disable coin slot rounding (allow for coins to fill up fractions of a slot the same way small items can)
- XP to level 2 (Allows GMs to raise or lower the XP requirements to level up)
- Allow negative ability scores / custom ability score min and max values

**Comment by Lee-Talman** [comment]
Turning these features on/off, and generally adding system settings in general, is definitely on the to-do list. I'm going to handle the smaller bugs and short-term fixes first for a 0.2.2 release, then system settings will likely be the key feature for 0.3.0.
